### ISSUE TITLE
Problems with G-Earth 1.3 Unity and qtConsole

### ISSUE THREAD

**Issue by sep1** [sirjonasxx/G-Earth#76] opened 2020-12-31 22:29 UTC
1) Habbo Unity gives me an all black screen and nothing happens:
https://imgur.com/OWQopF0
(Flash works fine)

2) "Enable G-Python scripting" gives me the following error:
https://imgur.com/MIxJIrg

Note that all the the required packages are installed (qtconsole pyqt5 jupyter-console g-python):
https://imgur.com/pqUMlbe

Even the chrome extension is installed.

**Comment by sirjonasxx** [comment] 2021-01-01 03:25
for the first error, please do the following;

* show a screenshot of the files inside the Cache/ folder, and of the folders in that folder (I need to see file sizes as well
* Run g-earth via commandline and if there are any errors, put a screenshot here (more info on how to do this at the bottom of https://github.com/sirjonasxx/G-Earth/wiki/Troubleshooting)
* Make sure that, when trying to reproduce, you delete the Cache folder every time


For your second issue, post a screenshot or a pastebin of the output of "python --version" and "python -m pip list"

**Comment by sep1** [comment] 2021-01-01 10:22
Deleting the Cache folder solved the first problem. Here is the error sometimes i get executing G-Earth.jar: https://pastebin.com/JkAiPRbz

I'm still having the second issue, here it is the pip list screen:
https://imgur.com/TGbLRns
Python version is 3.9.1

Thanks.

**Comment by sep1** [comment] 2021-01-09 09:57
Still having the issue with the live scripting console... Is there any solution?

**Comment by sirjonasxx** [comment] 2021-01-17 04:06
gonna close this one because its a duplicate of your isssue the in g-python repo https://github.com/sirjonasxx/G-Python/issues/10, lmk if the provided solution worked

**Closed by sirjonasxx** 2021-01-17 04:06 UTC
